apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tasks-app/kubernetes
    repoURL: https://github.com/Elad220/demo-ci-codebase.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true