name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - "**.js"
  # pull_request:
  #   branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env: # Or as an environment variable
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repo_name: "kub-tasks-api"

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file Dockerfile --tag "$dockerhub_username/$repo_name:$git_hash"
        echo $dockerhub_password | docker login -u $dockerhub_username --password-stdin
        docker push "$dockerhub_username/$repo_name:$git_hash"

# git_hash=$(git rev-parse --short "$GITHUB_SHA")
# docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .