name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - "users-api/users-app.js"

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repo_name: "kub-users"
      folder_name: "users-api"
      deployment_name: "users-deployment.yaml"

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd $folder_name/
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file Dockerfile --tag "$dockerhub_username/$repo_name:$git_hash"
        echo $dockerhub_password | docker login -u $dockerhub_username --password-stdin
        docker push "$dockerhub_username/$repo_name:$git_hash"
    - name: Update Version
      run: |
          cd $folder_name/kubernetes/
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./$deployment_name | grep image | awk '{print $2}')
          sed -i "s|$version|$dockerhub_username/$repo_name:$git_hash|g" ./$deployment_name

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated
        pull: '--rebase'